services:
  postgres:
    image: postgres:17
    container_name: team-todo-postgres
    environment:
      POSTGRES_DB: team_todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - team_todo_data:/var/lib/postgresql/data

volumes:
  team_todo_data: