spring.application.name=teamtodo

spring.datasource.url=jdbc:postgresql://localhost:5432/team_todo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.configuration.map-underscore-to-camel-case=true

server.port=8081